[package]
name        = "arenite-physics"
description = "Rapier2d rigidbody physics integration for Arenite Engine"
version.workspace    = true
authors.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true

[dependencies]
arenite-core.workspace = true
arenite-sim.workspace  = true
rapier2d.workspace          = true
crossbeam-channel.workspace = true
serde.workspace        = true
log.workspace          = true
ahash.workspace        = true
